sudo: false

language: php

php:
  - 7.2
  - 7.1

install:
  - composer install

script:
  - if [[ "$TRAVIS_PHP_VERSION" == '7.1' ]]; then phpunit --coverage-clover=coverage.clover ; fi
  - if [[ "$TRAVIS_PHP_VERSION" != '7.1' ]]; then phpunit ; fi

after_script:
  - if [[ "$TRAVIS_PHP_VERSION" == '7.1' ]]; then wget https://scrutinizer-ci.com/ocular.phar ; fi
  - if [[ "$TRAVIS_PHP_VERSION" == '7.1' ]]; then php ocular.phar code-coverage:upload --format=php-clover coverage.clover ; fi
