sudo: false

language: php

php:
  - hhvm
  - 7.1
  - 7.0
  - 5.6
  - 5.5

install:
  - if [[ "$TRAVIS_PHP_VERSION" == '5.5' ]]; then composer install ; fi
  - if [[ "$TRAVIS_PHP_VERSION" != '5.5' ]]; then composer require hanneskod/readme-tester:^1.0@beta ; fi

script:
  - if [[ "$TRAVIS_PHP_VERSION" == '7.0' ]]; then vendor/bin/phpunit --coverage-clover=coverage.clover ; fi
  - if [[ "$TRAVIS_PHP_VERSION" != '7.0' ]]; then vendor/bin/phpunit ; fi

after_script:
  - if [[ "$TRAVIS_PHP_VERSION" == '7.0' ]]; then wget https://scrutinizer-ci.com/ocular.phar ; fi
  - if [[ "$TRAVIS_PHP_VERSION" == '7.0' ]]; then php ocular.phar code-coverage:upload --format=php-clover coverage.clover ; fi
